# Generated by Django 5.1.7 on 2025-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_date', models.DateField(verbose_name='ფასდაკლების ვადა')),
                ('set_date', models.DateField(auto_now_add=True, verbose_name='დაყენების თარიღი')),
            ],
            options={
                'verbose_name': 'ფასდაკლება',
                'verbose_name_plural': 'ფასდაკლებები',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='სრული სახელი')),
                ('companyName', models.CharField(max_length=100, verbose_name='კომპანიის სახელი')),
                ('email', models.EmailField(max_length=254, verbose_name='ელ. ფოსტა')),
                ('address', models.TextField(verbose_name='მისამართი')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='ლოგო')),
                ('partner_valid_date', models.DateField(verbose_name='პარტნიორობის ვადა')),
            ],
            options={
                'verbose_name': 'პარტნიორი',
                'verbose_name_plural': 'პარტნიორები',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('storage_quantity', models.PositiveIntegerField(default=0, verbose_name='საწყობში რაოდენობა')),
                ('filter_setting', models.CharField(blank=True, max_length=50, verbose_name='ფილტრის პარამეტრი')),
            ],
            options={
                'verbose_name': 'პროდუქტი',
                'verbose_name_plural': 'პროდუქტები',
            },
        ),
    ]
