# Generated by Django 5.1.7 on 2025-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ფასდაკლების პროცენტი'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(to='web.product', verbose_name='პროდუქტები'),
        ),
    ]
