# Generated by Django 5.1.7 on 2025-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True, verbose_name='კოდი'),
        ),
    ]
