# Generated by Django 5.1.7 on 2025-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mobile',
            field=models.CharField(default='არ არის მითითებული', max_length=50, verbose_name='საკონტაქტო ნომერი'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=60, verbose_name='მისამართი'),
        ),
    ]
