# Generated by Django 5.1.7 on 2025-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_partner_mobile_alter_partner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=100, verbose_name='პროდუქცია')),
                ('clients', models.CharField(max_length=100, verbose_name='შემძენი')),
                ('price', models.CharField(max_length=100, verbose_name='ფასი')),
                ('addrs', models.CharField(max_length=100, verbose_name='მისამართი')),
                ('date', models.CharField(max_length=100, verbose_name='შეკვეთის დრო')),
                ('paymethod', models.CharField(max_length=100, verbose_name='გადახდის მეთოდი')),
                ('status', models.CharField(default='pedding', max_length=100, verbose_name='სტატუსი')),
            ],
            options={
                'verbose_name': 'შეკვეთა',
            },
        ),
    ]
