# Generated by Django 5.1.7 on 2025-04-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_detal',
            field=models.CharField(blank=True, max_length=70, verbose_name='ფილტრის პარამეტრი (ფსევდო)'),
        ),
    ]
