# Generated by Django 5.1.7 on 2025-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_product_filter_detal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_detal',
        ),
    ]
